### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by dlorenz70** [dmako/OpenCvSharpVisualizer#1]
I have installed the latest release with the .vsix and shows up as installed in Visual Studio, but when I try to show a Mat, it shows ![image](https://github.com/user-attachments/assets/05efe89b-7cf9-4295-86f6-63336fd5e69a)  

Any idea what might be wrong?

**Comment by dmako** [comment]
Hi @dlorenz70, the error you're seeing is not from my visualizer, but from the visualiser that was part of opencvsharp v3 repository, that one is not compatible with Visual Studio 2022. Most probably you have copied it there by yoursef. Try to delete it to get rid of the error message, my extension should not be affected.
